import openai
import re
import os
from dotenv import load_dotenv
load_dotenv()

openai.api_key = os.getenv("OPEN_AI_KEY")

def chatgpt(user_input):
    '''
    This function connects to the OpenAI GPT model using the provided user input.
    It initiates a chat conversation with the model and returns the response generated by GPT.
    
    Parameters:
    user_input (str): The user's input or prompt for generating a response. For our case is prompt for generating some jokes. 
    
    Returns:
    list of str: A list of responses generated by the GPT model. For our case is a list of jokes.
    '''
    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=[
                {"role": "system", "content": "You are a joke generator"},
                {"role": "system", "content": "You only provide direct answer without extra desciption phrases to the answer"},
                {"role": "user", "content": user_input},
            ]
    )
    results = response.choices[0].message.content
    results = re.split(r'\d+\.\s*', results)[1:]
    results = [string.replace("\n", "").replace("\ ", "") for string in results]
    return results



if __name__ == "__main__":
    import time 
    start = time.time()
    prompt = "give me 5 jokes about school for a 21 years old girl who is chinese and stays in Malaysia"
    output = chatgpt(prompt)
    end = time.time()
    print(output)
    print(end - start)
    print(len(output))